version: "3.2"
services:
  chip:
    build:
        context: ./
        dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=dev
    ports:
        - 8080:8080
    volumes:
        - ./:/go/src/chip
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.5'
          memory: 120M