basePath: /
definitions:
  healthcheck.Healthcheck:
    properties:
      description:
        type: string
      status:
        type: integer
    required:
    - description
    - status
    type: object
  reflect.Request:
    properties:
      body:
        type: string
      cookies:
        type: string
      headers:
        type: string
      method:
        type: string
      params:
        type: string
      path:
        type: string
    required:
    - body
    - cookies
    - headers
    - method
    - params
    - path
    type: object
  system.Capabilities:
    properties:
      cpus:
        type: integer
      hostname:
        type: string
      hypervisor:
        type: string
      memory:
        type: integer
      os:
        type: string
    required:
    - cpus
    - hostname
    - hypervisor
    - memory
    - os
    type: object
info:
  contact:
    email: matheus@nanoshots.com.br
    name: API Support
  description: Cloud Native Toolset Running in Containers.
  license:
    name: MIT
    url: https://github.com/mfidelis/chip/blob/master/LICENSE
  termsOfService: http://swagger.io/terms/
  title: Chip
  version: "1.0"
paths:
  /burn/cpu:
    get:
      produces:
      - application/json
      summary: Burn CPU for Loadtests and Auto Scaling Tests
      tags:
      - Loadtest
  /burn/ram:
    get:
      produces:
      - application/json
      summary: Burn RAM for Loadtests and Auto Scaling Tests
      tags:
      - Loadtest
  /healthcheck:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/healthcheck.Healthcheck'
      summary: Return 200 status Ok in healthcheck
      tags:
      - Healthcheck
  /healthcheck/error:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/healthcheck.Healthcheck'
      summary: Return 500 Error Status Code
      tags:
      - Healthcheck
  /healthcheck/fault:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/healthcheck.Healthcheck'
      summary: Inject common errors in healthcheck
      tags:
      - Healthcheck
  /healthcheck/fault/soft:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/healthcheck.Healthcheck'
      summary: Inject ocasional erros in healthcheck
      tags:
      - Healthcheck
  /reflection:
    delete:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/reflect.Request'
      summary: Retun request parameters in response for transformation tests
      tags:
      - Reflection
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/reflect.Request'
      summary: Retun request parameters in response for transformation tests
      tags:
      - Reflection
    patch:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/reflect.Request'
      summary: Retun request parameters in response for transformation tests
      tags:
      - Reflection
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/reflect.Request'
      summary: Retun request parameters in response for transformation tests
      tags:
      - Reflection
    put:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/reflect.Request'
      summary: Retun request parameters in response for transformation tests
      tags:
      - Reflection
  /system:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/system.Capabilities'
      summary: Return 500 Error Status Code
      tags:
      - System
  /system/environment:
    get:
      produces:
      - application/json
      summary: Dump all environment variables in container
      tags:
      - System
  /version:
    get:
      produces:
      - application/json
      summary: Return version for container
      tags:
      - Version
swagger: "2.0"
